create table
  public.email_log (
    id bigint generated by default as identity not null,
    idempotency_id text not null,
    user_id uuid null,
    sender text not null,
    recipient text not null,
    recipient_full_name text null,
    reply_to text not null,
    bcc text[] not null default '{}'::text[],
    attachment_paths text[] not null default '{}'::text[],
    subject text not null,
    body_text text null,
    body_html text null,
    created_at timestamp with time zone not null default now(),
    constraint email_log_pkey primary key (id),
    constraint email_log_user_id_idempotency_id_key unique (user_id, idempotency_id),
    constraint email_log_user_id_fkey foreign key (user_id) references auth.users (id)
  ) tablespace pg_default;

  -- We only enable RLS so FE cannot query this table.
  ALTER TABLE public.email_log ENABLE ROW LEVEL SECURITY;