AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  voxana edge function for non-trivial frontend calls (like voice uploads, not from PostgREST)

# Would we nice to set up Gateway Responses
Globals:
  Api:
    # This seem to NOT work, you still need to go Resource -> Endpoint -> Enable CORS manually.
    # https://us-east-1.console.aws.amazon.com/apigateway/home?region=us-east-1#/apis/xz067dkee6/resources/9l1jo7/enable-cors
    # TODO(P2, learning): Nice to learn more about CORS, getting annoying vibes from my friends.
    # AWS Proxy Integration and CORS:
    # In the AWS API Gateway, CORS (Cross-Origin Resource Sharing) is not enabled by default.
    # It needs to be enabled manually for each method.
    # This allows a server to indicate any other origins (domain, scheme, or port) than its own from which a browser
    # should permit loading of resources.
    #
    # When a proxy integration is used, the server (e.g., a Lambda function) behind it *must return*
    # the Access-Control-Allow-Origin header (and other Access-Control-* headers as needed) in the response.
    # The AWS API Gateway will not add these headers for you in a proxy integration,
    # as it passes the response from the backend service through to the client directly.
    # This differs from non-proxy integrations, where you can add these headers in the API Gateway response itself.
    Cors:
      AllowOrigin: "'https://app.voxana.ai,http://localhost:3000'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'GET,POST,OPTIONS'"
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
#  VoiceUploadsInvokePermission:
#    Type: AWS::Lambda::Permission
#    Properties:
#      Action: lambda:InvokeFunction
#      FunctionName: !GetAtt VoiceUploadsFunction.Arn
#      Principal: apigateway.amazonaws.com
#      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoxanaApi}/Prod/GET/upload/voice"

  VoiceUploadsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: upload_voice/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: requests-from-api-voxana
      Events:
        VoiceUploads:
          Type: Api
          Properties:
            Path: /upload/voice
            Method: get
#            RestApiId:
#              Ref: VoxanaApi

#  VoxanaApi:
#    Type: AWS::Serverless::Api
#    Properties:
#      # TODO(P1, privacy): Fine for now as no PII is sent over wire, but currently we have Detailed logging enabled
#      #   for all events: this can be useful to troubleshoot APIs, but can result in logging sensitive data.
#      # https://us-east-1.console.aws.amazon.com/apigateway/home?region=us-east-1#/apis/xz067dkee6/stages/Prod
#      StageName: Prod
#      Cors: "'https://app.voxana.ai,http://localhost:3000'"
#      DefinitionBody:
#        swagger: '2.0'
#        info:
#          title: Voxana API
#        paths:
#          /upload/voice:
#            get:
#              x-amazon-apigateway-integration:
#                httpMethod: GET
#                type: aws_proxy
#                uri:
#                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VoiceUploadsFunction.Arn}/invocations

# TODO(P2, devops): This would be nice, BUT it requires specifying VoxanaApi which completely messed up things.
# While per-method throttling settings allow for control at the API endpoint level,
# usage plans in Amazon API Gateway provide an additional layer of control and functionality.
# There are several reasons why you might choose to use usage plans:
#        x-amazon-apigateway-usageplan:
#          name: VoxanaUsagePlan
#          description: A usage plan for Voxana API
#          apiStages:
#            - apiId:
#                Ref: VoxanaApi
#              stage: Prod
#          throttle:
#            burstLimit: 10
#            rateLimit: 1
#      MethodSettings:
#        - ResourcePath: "/*"
#          HttpMethod: "*"
#          ThrottlingBurstLimit: 10
#          ThrottlingRateLimit: 1

# TODO(P1, auth): Currently, this API is publicly accessible kinda anonymously so we just ThrottlingRateLimit: 86440/day
# https://chat.openai.com/share/eb21a02b-59f0-4852-8fd9-ca674b9e5fcb
#   We should somehow limit this.
# Best way likely:
#  MyCustomAuthorizerFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: custom_authorizer/
#      Handler: app.lambda_handler
#      Runtime: python3.9
# Alternative:
#   AWS WAF has per-IP or Lambda@Edge will add more complexity to your setup, and you might incur additional costs.

#Outputs:
#  VoiceUploadsApi:
#    Description: "API Gateway endpoint URL for Prod stage for Voice Uploads function"
#    Value: !Sub "https://${VoxanaApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"
#  VoiceUploadsFunction:
#    Description: "Voice Uploads Lambda Function ARN"
#    Value: !GetAtt VoiceUploadsFunction.Arn
#  VoiceUploadsFunctionIamRole:
#    Description: "Implicit IAM Role created for Voice Uploads function"
#    Value: !GetAtt VoiceUploadsFunctionRole.Arn
