create table
  public.onboarding (
    id bigint generated by default as identity not null,
    ip_address text null,
    referer text null,
    utm_source text null,
    email text null,
    constraint onboarding_pkey primary key (id),
    -- one onboarding per email
    constraint email_key unique (email)
  ) tablespace pg_default;

  -- We only enable RLS so FE cannot query this table.
 ALTER TABLE public.onboarding ENABLE ROW LEVEL SECURITY;
