create table
  public.task (
    id bigint generated by default as identity not null,
    data_entry_id uuid not null,
    pipeline_id bigint not null,
    code_version text null, -- version of the code that executed the task
    state text not null default 'initiated'::text,
    retries_count bigint not null default '0'::bigint,
    drafted_output json null,
    api_response json null,
    created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    udpated_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    constraint task_pkey primary key (id),
    constraint task_data_entry_id_fkey foreign key (data_entry_id) references data_entry (id) on delete restrict,
    constraint task_pipeline_id_fkey foreign key (pipeline_id) references pipeline (id) on delete restrict,
    UNIQUE(data_entry_id, pipeline_id)
  ) tablespace pg_default;
ALTER TABLE public.task ENABLE ROW LEVEL SECURITY;

-- Link PromptLog to it
ALTER TABLE public.prompt_log ADD COLUMN task_id uuid null;
ALTER TABLE public.prompt_log ADD constraint prompt_log_task_id_fkey foreign key (task_id) references task (id) on delete set null;